"""listed_companies 에 market_cap · market_cap_updated_at 추가

자동완성 랭킹을 시가총액으로 가중하기 위한 컬럼이다. 값은 하루 1회 pykrx 배치가
채우며, 배치 전이거나 KRX 에 없는 종목은 NULL 로 남아 랭킹에서 뒤로 밀린다.

`batch_alter_table` 은 SQLite 의 좁은 ALTER TABLE 을 우회하려던 흔적이다. 그 시절
주 DB 가 SQLite 였고, 지금은 아니다 — Postgres 에서 batch 모드는 그대로 ALTER 로
내려가므로 동작에 차이가 없다. **이미 적용된 리비전이라 다시 쓰지 않는다.**
새 마이그레이션에는 쓰지 말 것 (`alembic/env.py` 주석 참고).

**뿌리가 아니게 됐다.** 예전에는 이 리비전이 `down_revision=None` 이라 사슬이
"있지도 않은 테이블에 컬럼을 더하는 것" 으로 시작했다. 빈 DB 에 `upgrade head` 를
돌리면 여기서 `UndefinedTable` 로 멈췄다는 뜻이다. `b0d3a1c7e594`(baseline)를 앞에
넣어 그 구멍을 메웠다 — 이 파일에서 바뀐 것은 `down_revision` 한 줄뿐이다.

Revision ID: 61b513b1f58a
Revises: b0d3a1c7e594
Create Date: 2026-07-31 14:11:04.042956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b513b1f58a'
down_revision: Union[str, Sequence[str], None] = 'b0d3a1c7e594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listed_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_cap', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('market_cap_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_listed_companies_market_cap'), ['market_cap'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listed_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listed_companies_market_cap'))
        batch_op.drop_column('market_cap_updated_at')
        batch_op.drop_column('market_cap')

    # ### end Alembic commands ###
